sudo: required
install:
    - sudo su
    - apt-get update && apt-get install git ebtables qemu-kvm bridge-utils bison flex libdb-dev
    - pushd /tmp/
    - git clone https://kernel.googlesource.com/pub/scm/linux/kernel/git/shemminger/iproute2
    - cd iproute2
    - git checkout v4.2.0
    - make
    - sudo make install
    - popd
    - git clone https://github.com/miniworld-project/miniworld_core.git
    - pushd miniworld_core
    - git checkout nightly
    - pip install -r requirements.txt
language: python
python:
    - "2.7"
# command to run tests
script: 
    - echo $PWD
    - ls
    - pushd tests/acceptance
    - pytest
