sudo: required
install:
    - sudo apt-get update && sudo apt-get install git ebtables qemu-kvm bridge-utils bison flex libdb-dev
    - pip install pytest
    #- pushd /tmp/
    #- git clone https://kernel.googlesource.com/pub/scm/linux/kernel/git/shemminger/iproute2
    #- cd iproute2
    #- git checkout v4.2.0
    #- make
    #- sudo make install
    #- popd
    #- git clone https://github.com/miniworld-project/miniworld_core.git
    #- pushd miniworld_core
    #- git checkout nightly
    #- sudo -E pip install -r requirements.txt
language: python
python:
    - "2.7"
# command to run tests
script: 
    - echo $PWD
    - ls
    #- pushd tests/acceptance
    #- popd
    - ls /dev/|grep kvm
    - sudo chown -R root:root /home/travis/virtualenv/python2.7
    - chmod +x /home/travis/virtualenv/python2.7/bin/activate 
    - sudo sh -c "/home/travis/virtualenv/python2.7/bin/activate && pytest"
